### PR TITLE
do not initialize session if uneeded

### PR DESCRIPTION
**Pull request by jaredhanson**
#320, plus edits for coding style

### CODE REVIEW

**Comment by analog-nico** [comment]
This change epically fails Passport powered apps: No login is possible anymore.

The technical details:

Many Passport strategies (e.g. passport-bitly, passport-stackexchange, passport-youtube-v3) have passport-oauth 0.1.x as a dependency. passport-oauth 0.1.x has passport ~0.1.1 as a dependency. As the result npm installs its own passport version for those strategies.

If the project uses the latest Passport version `passport.initialize()` will run the new code in `lib/middleware/initialize.js` and not initialize the session if the user is not logged in already. If then `req.logIn(...)` is called Passport goes through the strategies and should initialize the session in `lib/http/request.js`. However, the strategies mentioned above have their own passport version and they still use the old version of `lib/http/request.js` which does not initialize the session. As a result the login fails because of an assignment to `req._passport.session` which is not initialized.

This effect is so critical that we should find a general solution. These are the options I see:
1. Update all strategies that still use passport-oauth 0.1.x. This is a Sisyphus task since we would need to reach all the different strategy authors. I will go for that for the strategies that matter to me but since the failure is so critical this solution is rather slow.
2. Publish a 0.1.16 of passport-oauth which provides an interims fix.

Since you started working on solution 1 in issue #400 I just add this comment for reference.

**Comment by jaredhanson** [comment]
I've published passport@0.3.1, which was patched by #435.  The fix addresses issues when using older strategies that overwrite the improved, lazy session creation added in passport@0.3.x.

**Comment by analog-nico** [comment]
Thanks for the update @jaredhanson ! I tested it and it works like a charm.

Because of this update all the issues I opened for the strategies are not critical anymore. Would you like me to update the title of all issues or add another comment?

**Comment by jaredhanson** [comment]
I'm sure the strategy developers would appreciate the update, so yes.  Thanks for the report!

**Comment by analog-nico** [comment]
Done. Thanks again!

**Pull request merged**
