### PR TITLE
Address Session Fixation Concerns

### PR DESCRIPTION
**Pull request by jaredhanson**
This PR addresses session fixation concerns.  Anytime a user logs in or logs out, the session is regenerated (resulting in a new session ID).

### CODE REVIEW

**Comment by sushiljainam** [comment]
No reviews, No assignees.
This PR includes breaking changes - https://github.com/jaredhanson/passport/pull/900 
This error crashed our PRODUCTION.

No mention of **BREAKING CHANGE**
in changelog, in commit messages, in release guide, in migration guide
well there is no migration guide at all.
and there are no release docs - https://github.com/jaredhanson/passport/releases/tag/v0.6.0 mentions nothing of what includes

This is a REPO having 20k+ stars, 1.2k forks, consistent 1M+ weekly downloads on [npm](https://www.npmjs.com/package/passport)

Please make BREAKING CHANGES more visible and informed.

@jaredhanson

**Comment by jaredhanson** [comment]
> No reviews, No assignees.

I'm the only person who maintains this project.

> in changelog

It's listed here: https://github.com/jaredhanson/passport/blob/master/CHANGELOG.md#060---2022-05-20

> in migration guide

and here: https://medium.com/passportjs/fixing-session-fixation-b2b68619c51d

**Comment by sushiljainam-gt** [comment]
changelog was updated after the version was released.
and finding that medium blog link from repo or npm module is not possible or easy.

I appreciate your efforts and response, but for such a popular module
making it difficult for people to find changes and breaking changes feels reckless.
You can also add some contributors from community, I think many people are ready to help in this.
I am also ready to help if possible.

**Comment by sushiljainam** [comment]
changelog was updated after the version was released.
and finding that medium blog link from repo or npm module is not possible or easy.

I appreciate your efforts and response, but for such a popular module
making it difficult for people to find changes and breaking changes feels reckless.
You can also add some contributors from community, I think many people are ready to help in this.
I am also ready to help if possible.

**Comment by tgroutars** [comment]
@sushiljainam honestly it's on you for upgrading a non stable package without checking what changed first, don't come at the maintainer like that when you're clearly the one in the wrong

https://semver.org/#spec-item-4
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by sushiljainam** [comment]
I agree to you @tgroutars, 
but this module has gained so much popularity in its life of 11 years to still be in 0.y.z format.
And you can see in Issues section of this repo, that many people are concerned about this same breaking change.

Also my suggestion, maintainer should add few more maintainers who can welcome community contributions faster as he gets less time, which is completely okay.

Anyway, I learned this new thing about version starting with 0 (0.y.z), So yeah, I'll take care in future.
Thanks.

And Respect for @jaredhanson for creating and maintaining such a popular OSS.

**Comment by wmurphyrd** [comment]
> No reviews, No assignees. This PR includes breaking changes - #900 This error crashed our PRODUCTION.
> 
> No mention of **BREAKING CHANGE** in changelog, in commit messages, in release guide, in migration guide well there is no migration guide at all. and there are no release docs - https://github.com/jaredhanson/passport/releases/tag/v0.6.0 mentions nothing of what includes
> 
> This is a REPO having 20k+ stars, 1.2k forks, consistent 1M+ weekly downloads on [npm](https://www.npmjs.com/package/passport)
> 
> Please make BREAKING CHANGES more visible and informed.

@sushiljainam 
this comment could have been kinder, but I'm glad it's here because I also did not catch that there were breaking changes from the changelog entry and was about to merge the dependabot PR :pray:

**Pull request merged**
