### PR TITLE
Add support for promises on req.login.

### LINKED ISSUE #225: Promises
I have the following code:

```
	user.save()
		.then(function () {
			req.login(user, function (err) {
				if (err) {
					next(err);
				} else {
					auth.login(req, res);
				}
			});
		})
		.error(function (err) {
			winston.err(err);
		});
```

It would be nicer as:

```
	user.save()
		.then(function () {
			return req.login(user);
		})
		.then(function () {
			auth.login(req, res);
		})
		.error(function (err) {
			winston.err(err);
		});
```

If I added support for promises to passport, would you merge it?

### PR DESCRIPTION
**Pull request by Dignifiedquire**
In response to #227 this uses promise.

Closes #225.

### CODE REVIEW

**Comment by topaxi** [comment]
Any news on this?

**Comment by listepo** [comment]
Ping

**Comment by jaredhanson** [comment]
On further consideration, I don't have any desire for Passport to support promise-style calling conventions.  If need be, it is very easy to promisify req.login specifically in applications that need it.

There's too many opinions and options about how async functions should be called in JavaScript.  If it's promises now, it'll be some ES* feature next.  I'll follow the lead of Node core for what they expose on http.ServerResponse.  If they do promises, Passport will, but not until then.

**Comment by callumacrae** [comment]
Promises are an ES6 feature… https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by listepo** [comment]
Express.js 5, Promises in all handlers  https://github.com/strongloop/express/issues/2259

**Comment by jaredhanson** [comment]
When Express 5 implements support for promises, I'll follow suit for Passport's middleware.  Additional calling styles to http.ServerRequest will follow what Node core does with their API.

**Comment by Nicholaiii** [comment]
https://github.com/expressjs/express/pull/2237

**Comment by nhooey** [comment]
@jaredhanson How can you promisify `req.logIn`?

**Comment by nhooey** [comment]
See issue #536 for adding promise support now that a lot of time has passed since this issue was created.

**Pull request closed without merging**
